from pathlib import Path
import hashlib

import pandas as pd

from data.utils import get_stack_data
from tools import stopwatch

# These are LLM-generated reserved words per language, with a few human additions.
# They're later filtered to the most 'important' features
raw_feature_names = [
    # Symbols
    "#",
    "# ",
    "#!",
    "#!/usr/bin/env",
    "#!/bin/",
    "#include <",
    "<?php",
    "?>",
    "/*",
    "/**",
    "/*!",
    "*/",
    "//",
    "// ",
    "///",
    "//!",
    "'''",
    "--",
    "-- ",
    "--[[",
    "--]]",
    '@"',
    "&&",
    "||",
    ";;",
    "[[",
    "]]",
    "$(",
    "${",
    "$@",
    "$#",
    "$?",
    "?.",
    "??",
    "??=",
    "!==",
    "===",
    "|-",
    ">-",
    "```",
    "`",
    "~~",
    "- [ ]",
    ":\\n\\t",
    "::<",
    ": ",
    ':"',
    ': "',
    '="',
    '= "',
    "='",
    "= '",
    ":=",
    "=>",
    "=> {",
    "=> (",
    "->",
    "::",
    ";\n",
    " | ",
    " & ",
    # C
    "_Bool",
    "_Complex",
    "_Imaginary",
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum ",
    "extern ",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct ",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    # C++
    "#include <iostream>",
    "#include <string>",
    "#include <vector>",
    "alignas",
    "alignof",
    "and",
    "and_eq",
    "asm",
    "atomic_cancel",
    "atomic_commit",
    "atomic_noexcept",
    "auto",
    "bitand",
    "bitor",
    "bool",
    "break",
    "case",
    "catch",
    "char",
    "char16_t",
    "char32_t",
    "class ",
    "compl",
    "concept",
    "const",
    "const_cast",
    "consteval",
    "constexpr",
    "constinit",
    "continue",
    "co_await",
    "co_return",
    "co_yield",
    "decltype",
    "default",
    "delete",
    "do",
    "double",
    "dynamic_cast",
    "else",
    "enum ",
    "explicit",
    "export",
    "extern",
    "false",
    "float",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "mutable",
    "namespace ",
    "new",
    "noexcept",
    "not",
    "not_eq",
    "nullptr",
    "operator",
    "or",
    "or_eq",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "requires",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "static_cast",
    "struct ",
    "switch",
    "template",
    "template<",
    "this ",
    "this.",
    "thread_local",
    "throw",
    "true",
    "try",
    "typedef",
    "typeid",
    "typename",
    "union",
    "unsigned",
    "using",
    "virtual",
    "void",
    "volatile",
    "wchar_t",
    "while",
    "xor",
    "xor_eq",
    "std::",
    "using namespace",
    "cout",
    "cin",
    "<<",
    ">>",
    # C-Sharp
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class ",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum ",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface ",
    "internal",
    "is",
    "lock",
    "long",
    "namespace ",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct ",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
    "record",
    "init",
    "async",
    "await",
    "partial",
    "yield",
    # CSS
    "@charset",
    "@container",
    "@font-face",
    "@import",
    "@keyframes",
    "@layer",
    "@media",
    "@namespace",
    "@page",
    "@supports",
    "background",
    "border",
    "color",
    "calc(",
    "display",
    "flex",
    "font",
    "grid",
    "margin",
    "padding",
    "position",
    "transform",
    "var(",
    ":root",
    "--",
    # Dart
    "abstract",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class ",
    "const",
    "continue",
    "covariant",
    "default",
    "deferred",
    "do",
    "dynamic",
    "else",
    "enum ",
    "export",
    "extends",
    "extension",
    "external",
    "factory",
    "false",
    "final",
    "finally",
    "for",
    "Function",
    "get",
    "hide",
    "if",
    "implements",
    "import ",
    "in",
    "interface ",
    "is",
    "late",
    "library",
    "mixin",
    "new",
    "null",
    "on",
    "operator",
    "part",
    "rethrow",
    "return",
    "set",
    "show",
    "static",
    "super",
    "switch",
    "sync",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "var",
    "void",
    "while",
    "with",
    "yield",
    # Diff
    "@@",
    "+++",
    "---",
    "deleted file mode",
    "diff --git",
    "index",
    "new file mode",
    "rename from",
    "rename to",
    "similarity index",
    # Go
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func ",
    "func(",
    "go",
    "goto",
    "if",
    "import ",
    "interface ",
    "map",
    "package ",
    "range",
    "return",
    "select",
    "struct ",
    "switch",
    "type",
    "var",
    # GraphQL
    "directive",
    "enum ",
    "extend",
    "false",
    "fragment",
    "implements",
    "input",
    "interface ",
    "mutation",
    "null",
    "on",
    "query",
    "scalar",
    "schema",
    "subscription",
    "true",
    "type",
    "union",
    # HTML
    "<!DOCTYPE",
    "<html",
    "<head",
    "<body",
    "<div",
    "<span",
    "<a ",
    "<script",
    "<style",
    "<title",
    "<link",
    "<meta",
    # Perl
    "break",
    "case",
    "continue",
    "default",
    "do",
    "else",
    "elsif",
    "for",
    "foreach",
    "given",
    "goto",
    "if",
    "last",
    "my",
    "next",
    "our",
    "package ",
    "redo",
    "return",
    "state",
    "sub",
    "undef",
    "unless",
    "use",
    "when",
    "while",
    # PHP
    "php",
    "abstract",
    "and",
    "array",
    "as",
    "break",
    "callable",
    "case",
    "catch",
    "class ",
    "clone",
    "const",
    "continue",
    "declare",
    "default",
    "die",
    "do",
    "echo",
    "else",
    "elseif",
    "empty",
    "enddeclare",
    "endfor",
    "endforeach",
    "endif",
    "endswitch",
    "endwhile",
    "eval",
    "exit",
    "extends",
    "final",
    "finally",
    "for",
    "foreach",
    "function ",
    "function(",
    "global",
    "goto",
    "if",
    "implements",
    "include",
    "include_once",
    "instanceof",
    "insteadof",
    "interface ",
    "isset",
    "list",
    "namespace ",
    "new",
    "null",
    "or",
    "print",
    "private",
    "protected",
    "public",
    "require",
    "require_once",
    "return",
    "static",
    "switch",
    "throw",
    "trait ",
    "true",
    "try",
    "unset",
    "use",
    "var",
    "while",
    "xor",
    "false",
    "yield",
    # Python
    "print(",
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class ",
    "continue",
    "def ",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from ",
    "global",
    "if",
    "import ",
    "in",
    "is",
    "lambda",
    "match",
    "case",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
    # R
    "FALSE",
    "Inf",
    "NA",
    "NA_character_",
    "NA_complex_",
    "NA_integer_",
    "NA_real_",
    "NULL",
    "NaN",
    "TRUE",
    "break",
    "else",
    "for",
    "function ",
    "function(",
    "if",
    "in",
    "next",
    "repeat",
    "while",
    "<-",
    "library(",
    "function(",
    "data.frame(",
    # Ruby
    "BEGIN",
    "END",
    "alias",
    "and",
    "begin",
    "break",
    "case",
    "class ",
    "def ",
    "defined?",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "false",
    "for",
    "if",
    "in",
    "module",
    "next",
    "nil",
    "not",
    "or",
    "redo",
    "rescue",
    "retry",
    "return",
    "self",
    "super",
    "then",
    "true",
    "undef",
    "unless",
    "until",
    "when",
    "while",
    "yield",
    # Rust
    "Self",
    "as",
    "async",
    "await",
    "break",
    "const",
    "continue",
    "crate",
    "dyn",
    "else",
    "enum ",
    "extern",
    "false",
    "fn ",
    "fn(",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "static",
    "struct ",
    "super",
    "trait ",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    # SCSS
    "@each",
    "@else",
    "@extend",
    "@for",
    "@forward",
    "@function",
    "@if",
    "@import",
    "@include",
    "@mixin",
    "@return",
    "@use",
    "@while",
    "$",
    "#{",
    # Shell
    "alias",
    "case",
    "coproc",
    "declare",
    "do",
    "done",
    "elif",
    "else",
    "esac",
    "export",
    "fi",
    "for",
    "function ",
    "function(",
    "if",
    "in",
    "local",
    "readonly",
    "select",
    "then",
    "time",
    "typeset",
    "unalias",
    "unset",
    "until",
    "while",
    # SQL
    "SELECT",
    "WHERE",
    "alter",
    "and",
    "as",
    "by",
    "case",
    "create",
    "delete",
    "distinct",
    "drop",
    "end",
    "from ",
    "full",
    "group",
    "having",
    "inner",
    "insert",
    "into",
    "is",
    "join",
    "left",
    "limit",
    "null",
    "offset",
    "on",
    "or",
    "order",
    "outer",
    "right",
    "select",
    "table",
    "then",
    "union",
    "update",
    "values",
    "when",
    "where",
    # Swift
    "Any",
    "Self",
    "_",
    "actor",
    "as",
    "associatedtype",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class ",
    "continue",
    "default",
    "defer",
    "deinit",
    "do",
    "else",
    "enum ",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "for",
    "func ",
    "func(",
    "guard",
    "if",
    "import ",
    "in",
    "init",
    "inout",
    "internal",
    "is",
    "let",
    "nil",
    "nonisolated",
    "open",
    "operator",
    "private",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "some",
    "static",
    "struct ",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "where",
    "while",
    # TypeScript
    "abstract",
    "any",
    "as",
    "asserts",
    "async",
    "await",
    "boolean",
    "break",
    "case",
    "catch",
    "class ",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum ",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function ",
    "function(",
    "if",
    "implements",
    "import ",
    "import(",
    "import{",
    "in",
    "infer",
    "instanceof",
    "interface ",
    "keyof",
    "let",
    "module",
    "namespace ",
    "never",
    "new",
    "null",
    "number",
    "object",
    "override",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "return",
    "static",
    "string",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
    "satisfies",
    "?:",
    "!:",
    # Visual_Basic_.NET
    "AddHandler",
    "AddressOf",
    "Alias",
    "And",
    "AndAlso",
    "As",
    "Boolean",
    "ByRef",
    "Byte",
    "ByVal",
    "Call",
    "Case",
    "Catch",
    "CBool",
    "CByte",
    "CChar",
    "CDate",
    "CDec",
    "CDbl",
    "Char",
    "CInt",
    "Class",
    "CLng",
    "CObj",
    "Const",
    "Continue",
    "CSByte",
    "CShort",
    "CSng",
    "CStr",
    "CType",
    "CUInt",
    "CULng",
    "CUShort",
    "Date",
    "Decimal",
    "Declare",
    "Default",
    "Delegate",
    "Dim",
    "DirectCast",
    "Do",
    "Double",
    "Each",
    "Else",
    "ElseIf",
    "End",
    "EndIf",
    "Enum",
    "Erase",
    "Error",
    "Event",
    "Exit",
    "False",
    "Finally",
    "For",
    "Friend",
    "Function",
    "Get",
    "GetType",
    "GetXMLNamespace",
    "Global",
    "GoSub",
    "GoTo",
    "Handles",
    "If",
    "Implements",
    "Imports",
    "In",
    "Inherits",
    "Integer",
    "Interface",
    "Is",
    "IsNot",
    "Let",
    "Lib",
    "Like",
    "Long",
    "Loop",
    "Me",
    "Mod",
    "Module",
    "MustInherit",
    "MustOverride",
    "MyBase",
    "MyClass",
    "Namespace",
    "Narrowing",
    "New",
    "Next",
    "Not",
    "Nothing",
    "NotInheritable",
    "NotOverridable",
    "Object",
    "On",
    "Operator",
    "Option",
    "Optional",
    "Or",
    "OrElse",
    "Overloads",
    "Overridable",
    "Overrides",
    "ParamArray",
    "Partial",
    "Private",
    "Property",
    "Protected",
    "Public",
    "RaiseEvent",
    "ReadOnly",
    "ReDim",
    "REM",
    "RemoveHandler",
    "Resume",
    "Return",
    "SByte",
    "Select",
    "Set",
    "Shadows",
    "Shared",
    "Short",
    "Single",
    "Static",
    "Step",
    "Stop",
    "String",
    "Structure",
    "Sub",
    "SyncLock",
    "Then",
    "Throw",
    "To",
    "True",
    "Try",
    "TryCast",
    "TypeOf",
    "UInteger",
    "ULong",
    "UShort",
    "Using",
    "When",
    "While",
    "Widening",
    "With",
    "WithEvents",
    "WriteOnly",
    "Xor",
    # WebAssembly
    "anyref",
    "data",
    "element",
    "export",
    "externref",
    "f32",
    "f64",
    "(func",
    "funcref",
    "global",
    "i32",
    "i64",
    "(import",
    "local",
    "memory",
    "module",
    "mut",
    "offset",
    "param",
    "result",
    "start",
    "table",
    "type",
    # YAML
    "---",
    "...",
    "- ",
    "?",
    "|",
    ">",
    "&",
    "*",
    "!",
    "~",
    "true",
    "false",
    "null",
    "Null",
    "NULL",
    # INI
    "[",
    "]",
    ";",
    # Java
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class ",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum ",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import ",
    "instanceof",
    "int",
    "interface ",
    "long",
    "native",
    "new",
    "null",
    "package ",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "true",
    "try",
    "void",
    "volatile",
    "while",
    "record",
    "sealed",
    "permits",
    "non-sealed",
    # JavaScript
    "console.",
    "await",
    "break",
    "case",
    "catch",
    "class ",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum ",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function ",
    "function(",
    "if",
    "import ",
    "import(",
    "import{",
    "in",
    "instanceof",
    "let",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
    "prototype",
    "require(",
    "module.exports",
    "exports.",
    # JSON
    "false",
    "null",
    "true",
    '":',
    '{"',
    '["',
    # Kotlin
    "abstract",
    "actual",
    "annotation",
    "as",
    "break",
    "by",
    "catch",
    "class ",
    "companion",
    "const",
    "constructor",
    "continue",
    "crossinline",
    "data",
    "delegate",
    "do",
    "dynamic",
    "else",
    "enum ",
    "expect",
    "external",
    "false",
    "field",
    "file",
    "final",
    "finally",
    "for",
    "fun ",
    "fun(",
    "get",
    "if",
    "implements",
    "import ",
    "in",
    "infix",
    "init",
    "inline",
    "inner",
    "interface ",
    "internal",
    "is",
    "lateinit",
    "noinline",
    "null",
    "object",
    "open",
    "operator",
    "out",
    "override",
    "package ",
    "param",
    "private",
    "property",
    "protected",
    "public",
    "receiver",
    "reified",
    "return",
    "sealed",
    "set",
    "setparam",
    "super",
    "suspend",
    "tailrec",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "val",
    "var",
    "vararg",
    "when",
    "where",
    "while",
    # Less
    "@arguments",
    "@charset",
    "@container",
    "@default",
    "@import",
    "@import (",
    "@keyframes",
    "@media",
    "@page",
    "@plugin",
    "@supports",
    "@rest",
    "@{",
    "each",
    "each(",
    "when",
    "when (",
    "&:extend",
    ".mixin(",
    # Lua
    "and",
    "break",
    "do",
    "else",
    "elseif",
    "end",
    "false",
    "for",
    "function ",
    "function(",
    "goto",
    "if",
    "in",
    "local",
    "nil",
    "not",
    "or",
    "repeat",
    "return",
    "then",
    "true",
    "until",
    "while",
    # Makefile
    "call",
    "define",
    "else",
    "endef",
    "endif",
    "error",
    "eval",
    "export",
    "ifdef",
    "ifndef",
    "ifeq",
    "ifneq",
    "include",
    "info",
    "override",
    "shell",
    "unexport",
    "vpath",
    "warning",
    "$(",
    "$(shell",
    ":=",
    "?=",
    "+=",
    "@echo",
    "%:",
    "\t",
    # XML
    "<![CDATA[",
    "<!DOCTYPE",
    "<?xml",
    "</",
    "/>",
    "xmlns",
    "<!--",
    # Markdown
    "```",
    "#",
    "##",
    "---",
    ">",
    "* ",
    "- ",
    "_",
    "[",
    "](",
    # Objective-C
    "@autoreleasepool",
    "@catch",
    "@class",
    "@dynamic",
    "@end",
    "@finally",
    "@implementation",
    "@import",
    "@interface",
    "@optional",
    "@private",
    "@property",
    "@protected",
    "@protocol",
    "@public",
    "@required",
    "@selector",
    "@synchronized",
    "@synthesize",
    "@try",
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum ",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct ",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "_Bool",
    "_Complex",
    "_Imaginary",
]

# dedupe and sort
feature_names = sorted(set(raw_feature_names))


def generate_features(df: pd.DataFrame | None = None, use_cache=True) -> pd.DataFrame:
    df = get_stack_data() if df is None else df
    lang_counts = df.Language.value_counts().sort_index()
    fingerprint = f"rows={len(df)}\nfeatures={'\n'.join(feature_names)}\n{lang_counts.to_string()}"
    data_hash = hashlib.sha256(fingerprint.encode("utf-8")).hexdigest()[:12]
    feature_file = Path(f"features/features_{data_hash}.parquet")

    if feature_file.exists() and use_cache:
        print(f"⚡ Using cached features from {feature_file}")
        return pd.read_parquet(feature_file)

    with stopwatch("extracting features"):
        features_matrix = []
        for snippet in df.Snippet:
            snippet = snippet.replace("\r\n", "\n").replace("\r", "\n")
            features = [feature_name in snippet for feature_name in feature_names]
            features_matrix.append(features)

    features_df = pd.DataFrame(features_matrix, columns=feature_names)
    features_df["Target"] = df.Language.to_list()

    features_df.to_parquet(feature_file, index=False)

    return features_df


if __name__ == "__main__":
    df = get_stack_data()
    features = generate_features(
        df=df.head(),
    )
