# Auto-generated from features.py sections.
FEATURE_NAMES = [
    'FALSE',
    'Inf',
    'NA',
    'NA_character_',
    'NA_complex_',
    'NA_integer_',
    'NA_real_',
    'NULL',
    'NaN',
    'TRUE',
    'break',
    'else',
    'for',
    'function ',
    'function(',
    'if',
    'in',
    'next',
    'repeat',
    'while',
    '<-',
    'library(',
    'function(',
    'data.frame(',
]
