# Auto-generated from features.py sections.
FEATURE_NAMES = [
    'console.',
    'await',
    'break',
    'case',
    'catch',
    'class ',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'enum ',
    'export',
    'extends',
    'false',
    'finally',
    'for',
    'function ',
    'function(',
    'if',
    'import ',
    'import(',
    'import{',
    'in',
    'instanceof',
    'let',
    'new',
    'null',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
    'prototype',
    'require(',
    'module.exports',
    'exports.',
    'abstract',
    'any',
    'as',
    'asserts',
    'async',
    'boolean',
    'declare',
    'implements',
    'infer',
    'interface ',
    'keyof',
    'module',
    'namespace ',
    'never',
    'number',
    'object',
    'override',
    'private',
    'protected',
    'public',
    'readonly',
    'require',
    'static',
    'string',
    'type',
    'undefined',
    'unknown',
    'satisfies',
    '?:',
    '!:',
]
